Name: Prep50Api
Repo: github.com/Prep50mobileApp/prep50-api
Version: main
Dest: ./
Module: prep50-api
DisableInlineCommands: false
NodePackageManager: npm
DisableNpmInstall: false
NpmBuildScriptName: build
Watcher:
    Disable: false
    Backend:
        - .go
        - .mod
        - .yml
        - .toml
        - .tml
        - .ini
        - .amber
    Frontend:
        - .html
        - .htm
        - .svelte
        - .md
        - .js
        - .ts
        - .jsx
        - .tsx
        - .css
        - .scss
        - .less
        - .json
        - .proto
    IgnoreDirs:
        - .github
        - .github/*
        - uploads
        - uploads/*
        - bin
LiveReload:
    Disable: false
    Port: 35729
Files:
    - ./
BuildFiles:
    - public/assets/validator.js
    - bin/prep50_ctl
    - bin/prep50
MD5PackageJSON: []
