app:
  name: Prep50
  host: "prep50.herokuapp.com"
  port: 8081
  key: ""
  version: "1"
  defaultApiVersion: 1.0.0
database:
  core:
    url:
    name: prep50?parseTime=true
    user: admin
    host: localhost
    port: 3306
    password:
  app:
    url:
    name: prep50app?parseTime=true
    user: admin
    host: localhost
    port: 3306
    password:
throttle:
  limit: 20
  burst: 5
aes:
  key: ""
  iv: ""
cors:
  origins:
    - prep50.com
    - localhost:8081
  headers: Accept,content-type,X-Requested-With,Content-Length,Accept-Encoding,accept-version,X-CSRF-Token,Authorization
  allowCredentials: "true"
jwt:
  access: 4320
  refresh: 20160
mail:
  username: efedua.bell@gmail.com
  from: prep50
  smtpHost: smtp.gmail.com
  smtpPort: 587
  password:
redis:
  host: 127.0.0.1
  port: 6379
  password: ""
  database: 0
