app:
  name: Prep50
  host: api.prep50.com
  port: 8081
  key: ""
  version: 1
  defaultApiVersion: 1.0.0
database:
  core:
    url: ikr3vl8eozfc3qba:t1rfqfvoq10tqe90@tcp(cxmgkzhk95kfgbq4.cbetxkdyhwsb.us-east-1.rds.amazonaws.com:3306)/ngbrgd16w9e3o40v?parseTime=true
    name:
    user:
    host:
    port:
    password:
  app:
    url: h4b2q7rlnq2esxvw:zkg6z2hznlawr3se@tcp(kfgk8u2ogtoylkq9.cbetxkdyhwsb.us-east-1.rds.amazonaws.com:3306)/xpjrbt2hy7943y8b?parseTime=true
    name:
    user:
    host:
    port:
    password:
throttle:
  limit: 20
  burst: 5
cors:
  origins:
    - prep50.com
  headers: "Accept,content-type,X-Requested-With,Content-Length,Accept-Encoding,accept-version,X-CSRF-Token,Authorization,token"
  allowCredentials: "true"
aes:
  key:
  iv:
# JWT expiration time in minutes
jwt:
  access: 15
  refresh: 168

mail:
  username: youremail@gmail.com
  password: youremailpasswordOrGmailAppPassword
  from: prep50
  smtpHost: smtp.gmail.com
  smtpPort: 587
