app:
  name: Prep50
  host: ""
  port: 8081
  key: ""
  version: "1"
  defaultApiVersion: 1.0.0
database:
  url:
  name: prep50
  user: root
  host:
  port:
  password:
throttle:
  limit: 20
  burst: 5
aes:
  key: ""
  iv: ""
cors:
  origins:
    - prep50.deacons.ng
  headers: Accept,content-type,X-Requested-With,Content-Length,Accept-Encoding,accept-version,X-CSRF-Token,Authorization,token
  allowCredentials: "true"
jwt:
  access: 20160
  refresh: 40320
mail:
  username: prep50mock
  from: Prep50
  smtpHost: mail.smtp2go.com
  smtpPort: 587
  password:
redis:
  host: 142.93.96.13
  port: 6380
  database: 0
