app:
  name: Prep50
  host: ""
  port: 8081
  key: ""
  version: "1"
  defaultApiVersion: 1.0.0
database:
  core:
    url:
    name: "prep50"
    user: root
    host: 142.93.96.13
    port: 3308
    password:
  app:
    url:
    name: "prep50_app"
    user: root
    host: 142.93.96.13
    port: 3308
    password:
throttle:
  limit: 20
  burst: 5
aes:
  key: ""
  iv: ""
cors:
  origins:
    - core.prep50.ng
    - api.prep50.ng
  headers: Accept,content-type,X-Requested-With,Content-Length,Accept-Encoding,accept-version,X-CSRF-Token,Authorization,token
  allowCredentials: "true"
jwt:
  access: 20160
  refresh: 40320
mail:
  username: efedua.bell@gmail.com
  from: prep50
  smtpHost: smtp.gmail.com
  smtpPort: 587
  password:
redis:
  host: 142.93.96.13
  port: 6380
  database: 0
