app:
  name: Prep50
  host:
  port: 8081
  key: ""
  version: 1
  defaultApiVersion: 1.0.0
database:
  core:
    url:
    name: prep50
    user: root
    host:
    port: 3306
    password: beLL1923
  app:
    url:
    name: prep50core
    user: root
    host:
    port: 3306
    password: beLL1923
throttle:
  limit: 20
  burst: 5
cors:
  origins:
    - prep50.com
  headers: "Accept,content-type,X-Requested-With,Content-Length,Accept-Encoding,accept-version,X-CSRF-Token,Authorization,token"
  allowCredentials: "true"
aes:
  key:
  iv:
# JWT expiration time in minutes
jwt:
  access: 15
  refresh: 168

mail:
  username: youremail@gmail.com
  password: youremailpasswordOrGmailAppPassword
  from: prep50
  smtpHost: smtp.gmail.com
  smtpPort: 587
