ARG LOG_STACK=${LOG_STACK}
ARG DB_APP_PASSWORD=${DB_APP_PASSWORD}
ARG DB_CORE_PASSWORD=${DB_CORE_PASSWORD}
ARG SETUP_EMAIL=${SETUP_EMAIL}
ARG SETUP_USERNAME=${SETUP_USERNAME}
ARG SETUP_PHONE=${SETUP_PHONE}
ARG SETUP_PASSWORD=${SETUP_PASSWORD}

FROM golang:1.20

ENV APP_NAME prep50
ENV APP_PATH /app

RUN apt update && apt install libvips-dev libvips-tools -y  

WORKDIR ${APP_PATH}/
ADD . ${APP_PATH}

ARG LOG_STACK
ARG DB_APP_PASSWORD
ARG DB_CORE_PASSWORD
ARG SETUP_EMAIL
ARG SETUP_USERNAME
ARG SETUP_PHONE
ARG SETUP_PASSWORD

RUN go build -o bin/${APP_NAME} main.go
RUN go build -o bin/${APP_NAME}_ctl cmd/prep50-ctl/prep50_ctl.go

ENV PORT 8080
EXPOSE ${PORT}

RUN ./bin/${APP_NAME} init -y

CMD ./bin/${APP_NAME}