ARG LOG_STACK=${LOG_STACK}
ARG DB_APP_PASSWORD=${DB_APP_PASSWORD}
ARG DB_CORE_PASSWORD=${DB_CORE_PASSWORD}
ARG SETUP_EMAIL=${SETUP_EMAIL}
ARG SETUP_USERNAME=${SETUP_USERNAME}
ARG SETUP_PHONE=${SETUP_PHONE}
ARG SETUP_PASSWORD=${SETUP_PASSWORD}

FROM golang:1.20

RUN apt update && apt install libvips-dev libvips-tools -y  

WORKDIR /app
COPY . .
RUN make && make ctl

EXPOSE 8081
ARG LOG_STACK
ARG DB_APP_PASSWORD
ARG DB_CORE_PASSWORD
ARG SETUP_EMAIL
ARG SETUP_USERNAME
ARG SETUP_PHONE
ARG SETUP_PASSWORD

EXPOSE 80

RUN ./bin/prep50_ctl init -y

ENV PORT 80
CMD ["./bin/prep50"]