exam.session:
qquiz.questions: 60
paystack.mode: "live"
paystack.live.secretKey: ""
paystack.live.publicKey: ""
paystack.sandbox.secretKey: "sk_test_26564ae24578cddeb710f465d89d125c9bdfe4f7"
paystack.sandbox.publicKey: "pk_test_af4e0ef7bfdedcb27859289c27fd2a97100f1ba1"
